export {
  type Actor,
  isShareLinkError,
  SHARE_LINK_ERROR_CODES,
  ShareLinkError,
  type ShareLinkErrorCode,
} from "./errors.js";
export {
  type AdmissionRefusal,
  admits,
  domainOf,
  emailRefusal,
  isLive,
  isOpen,
  LINK_POLICY_SCHEMA_VERSION,
  type LinkPolicy,
  type LinkPolicyRefusal,
  linkPolicyPermitted,
  normalizeAddress,
  normalizeDomain,
  normalizeLinkPolicy,
  OPEN_LINK_POLICY,
  PASSCODE_LOCK_MS,
  PASSCODE_MAX_ATTEMPTS,
  PASSCODE_MAX_LENGTH,
  PASSCODE_MIN_LENGTH,
  type PasscodeFacts,
  passcodeLockUntil,
  passcodeVerdict,
  policyNamesAnAudience,
  type ResolvedLink,
  SHARE_LINK_STATUSES,
  type ShareLinkStatus,
} from "./policy.js";
export { readForcedWatermark, ShareLinkRepo, toLinkRecord } from "./repos/share-link-repo.js";
export {
  createShareLinkProtection,
  type ForcedProtection,
  type ShareLinkProtectionService,
} from "./service/forced-protection.js";
export {
  createShareLinkAccess,
  createShareLinkService,
  type MintedLink,
  type MintLinkInput,
  type RedeemInput,
  type RedeemResult,
  type RevokeInput,
  type ShareLinkAccess,
  type ShareLinkService,
} from "./service/links.js";
export {
  type CreateShareLinkValues,
  createMemoryViewSessionLedger,
  databaseViewSessionLedger,
  type LinkRecord,
  type LinkSummary,
  type LinkVisit,
  type ListFilter,
  type ShareLinkDeps,
  type ShareLinkStore,
  toLinkSummary,
  toResolvedLink,
  VIEW_SESSION_LEDGER_MAX,
  type ViewSessionKey,
  type ViewSessionLedger,
  type VisitClaim,
} from "./service/types.js";
export {
  type CodeKeyRing,
  hashPasscode,
  isAcceptablePasscode,
  isPlausibleToken,
  mintToken,
  normalizePasscode,
  passcodeScope,
  SHARE_LINK_TOKEN_BYTES,
  SHARE_LINK_TOKEN_MIN_LENGTH,
  tokenHash,
  verifyPasscode,
} from "./token.js";
