export {
  type CryptoJobOptions,
  createCryptoJobs,
  createEnvelopeService,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_PURPOSE,
  type EnvelopeService,
  type EnvelopeServiceOptions,
  type EnvelopeStats,
  type WorkspaceDataKey,
} from "./envelope.js";
export { WorkspaceKeyRepo } from "./repos/workspace-key-repo.js";
export {
  buildHeader,
  bytesToStream,
  CHUNK_BYTES,
  CHUNK_CIPHERTEXT_BYTES,
  type CiphertextRange,
  ciphertextLength,
  ciphertextRangeFor,
  DEK_BYTES,
  type DecryptOptions,
  decryptBytes,
  decryptRange,
  decryptStream,
  type EncryptOptions,
  encryptBytes,
  encryptStream,
  FORMAT_VERSION,
  HEADER_BYTES,
  MAGIC,
  NONCE_BYTES,
  type PlaintextRange,
  parseHeader,
  plaintextLength,
  SALT_BYTES,
  StreamAeadError,
  type StreamAeadErrorCode,
  sliceStream,
  streamToBytes,
  TAG_BYTES,
} from "./stream-aead.js";
