{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fundroom.chartSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fundroom.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "fundroom.secretData" . | trim | nindent 2 }}
{{- end }}
