/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRequestAccessRouteImport } from './routes/_auth/request-access'
import { Route as AuthUnsubscribeRouteImport } from './routes/_auth/unsubscribe'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalSplatRouteImport } from './routes/_portal/$'
import { Route as PortalSearchRouteImport } from './routes/_portal/search'
import { Route as PortalSettingsRouteImport } from './routes/_portal/settings'
import { Route as PortalSignRouteImport } from './routes/_portal/sign'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformAuditRouteImport } from './routes/platform/audit'
import { Route as PlatformCellsRouteImport } from './routes/platform/cells'
import { Route as PlatformHealthRouteImport } from './routes/platform/health'
import { Route as PlatformOperatorsRouteImport } from './routes/platform/operators'
import { Route as PlatformPlansRouteImport } from './routes/platform/plans'
import { Route as PlatformEnrolRouteImport } from './routes/platform_.enrol'
import { Route as AuthAuthMagicLinkRouteImport } from './routes/_auth/auth/magic-link'
import { Route as AuthAuthPopupRouteImport } from './routes/_auth/auth/popup'
import { Route as AuthAuthStepUpRouteImport } from './routes/_auth/auth/step-up'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite/$token'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthLoginVerifyRouteImport } from './routes/_auth/login/verify'
import { Route as AuthSTokenRouteImport } from './routes/_auth/s/$token'
import { Route as PortalPSlugRouteImport } from './routes/_portal/p/$slug'
import { Route as PortalSettingsIndexRouteImport } from './routes/_portal/settings/index'
import { Route as PortalSettingsDelegatesRouteImport } from './routes/_portal/settings/delegates'
import { Route as PortalSettingsSecurityRouteImport } from './routes/_portal/settings/security'
import { Route as AdminAccessRequestsIndexRouteImport } from './routes/admin/access-requests/index'
import { Route as AdminAccessReviewIndexRouteImport } from './routes/admin/access-review/index'
import { Route as AdminAccreditationIndexRouteImport } from './routes/admin/accreditation/index'
import { Route as AdminApiKeysIndexRouteImport } from './routes/admin/api-keys/index'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as AdminBrandingIndexRouteImport } from './routes/admin/branding/index'
import { Route as AdminDomainsIndexRouteImport } from './routes/admin/domains/index'
import { Route as AdminEmbedIndexRouteImport } from './routes/admin/embed/index'
import { Route as AdminEsignIndexRouteImport } from './routes/admin/esign/index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups/index'
import { Route as AdminGroupsGroupIdRouteImport } from './routes/admin/groups/$groupId'
import { Route as AdminHealthIndexRouteImport } from './routes/admin/health/index'
import { Route as AdminIntegrationsIndexRouteImport } from './routes/admin/integrations/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminLegalIndexRouteImport } from './routes/admin/legal/index'
import { Route as AdminLegalDocumentIdRouteImport } from './routes/admin/legal/$documentId'
import { Route as AdminMailIndexRouteImport } from './routes/admin/mail/index'
import { Route as AdminModulesIndexRouteImport } from './routes/admin/modules/index'
import { Route as AdminPeopleIndexRouteImport } from './routes/admin/people/index'
import { Route as AdminPeopleMembershipIdRouteImport } from './routes/admin/people/$membershipId'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsAccessRouteImport } from './routes/admin/settings/access'
import { Route as AdminSettingsAiRouteImport } from './routes/admin/settings/ai'
import { Route as AdminSettingsDangerRouteImport } from './routes/admin/settings/danger'
import { Route as AdminSettingsExportRouteImport } from './routes/admin/settings/export'
import { Route as AdminSettingsResidencyRouteImport } from './routes/admin/settings/residency'
import { Route as AdminShareLinksIndexRouteImport } from './routes/admin/share-links/index'
import { Route as AdminSsoIndexRouteImport } from './routes/admin/sso/index'
import { Route as AdminWebhooksIndexRouteImport } from './routes/admin/webhooks/index'
import { Route as AdminWebhooksEndpointIdRouteImport } from './routes/admin/webhooks/$endpointId'
import { Route as PlatformSanctionsIndexRouteImport } from './routes/platform/sanctions/index'
import { Route as PlatformSanctionsIdRouteImport } from './routes/platform/sanctions/$id'
import { Route as PlatformWorkspacesIdRouteImport } from './routes/platform/workspaces/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestAccessRoute = AuthRequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnsubscribeRoute = AuthUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => AuthRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSplatRoute = PortalSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSearchRoute = PortalSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSignRoute = PortalSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCellsRoute = PlatformCellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformHealthRoute = PlatformHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOperatorsRoute = PlatformOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformEnrolRoute = PlatformEnrolRouteImport.update({
  id: '/platform_/enrol',
  path: '/platform/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthMagicLinkRoute = AuthAuthMagicLinkRouteImport.update({
  id: '/auth/magic-link',
  path: '/auth/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthPopupRoute = AuthAuthPopupRouteImport.update({
  id: '/auth/popup',
  path: '/auth/popup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthStepUpRoute = AuthAuthStepUpRouteImport.update({
  id: '/auth/step-up',
  path: '/auth/step-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginVerifyRoute = AuthLoginVerifyRouteImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSTokenRoute = AuthSTokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => AuthRoute,
} as any)
const PortalPSlugRoute = PortalPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsIndexRoute = PortalSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsDelegatesRoute = PortalSettingsDelegatesRouteImport.update({
  id: '/delegates',
  path: '/delegates',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsSecurityRoute = PortalSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const AdminAccessRequestsIndexRoute =
  AdminAccessRequestsIndexRouteImport.update({
    id: '/access-requests/',
    path: '/access-requests/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAccessReviewIndexRoute = AdminAccessReviewIndexRouteImport.update({
  id: '/access-review/',
  path: '/access-review/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccreditationIndexRoute = AdminAccreditationIndexRouteImport.update({
  id: '/accreditation/',
  path: '/accreditation/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysIndexRoute = AdminApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingIndexRoute = AdminBrandingIndexRouteImport.update({
  id: '/branding/',
  path: '/branding/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsIndexRoute = AdminDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmbedIndexRoute = AdminEmbedIndexRouteImport.update({
  id: '/embed/',
  path: '/embed/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEsignIndexRoute = AdminEsignIndexRouteImport.update({
  id: '/esign/',
  path: '/esign/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsGroupIdRoute = AdminGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthIndexRoute = AdminHealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalIndexRoute = AdminLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalDocumentIdRoute = AdminLegalDocumentIdRouteImport.update({
  id: '/legal/$documentId',
  path: '/legal/$documentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailIndexRoute = AdminMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesIndexRoute = AdminModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleIndexRoute = AdminPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleMembershipIdRoute = AdminPeopleMembershipIdRouteImport.update({
  id: '/people/$membershipId',
  path: '/people/$membershipId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsAccessRoute = AdminSettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsAiRoute = AdminSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsDangerRoute = AdminSettingsDangerRouteImport.update({
  id: '/settings/danger',
  path: '/settings/danger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsExportRoute = AdminSettingsExportRouteImport.update({
  id: '/settings/export',
  path: '/settings/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsResidencyRoute = AdminSettingsResidencyRouteImport.update({
  id: '/settings/residency',
  path: '/settings/residency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShareLinksIndexRoute = AdminShareLinksIndexRouteImport.update({
  id: '/share-links/',
  path: '/share-links/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSsoIndexRoute = AdminSsoIndexRouteImport.update({
  id: '/sso/',
  path: '/sso/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksIndexRoute = AdminWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksEndpointIdRoute = AdminWebhooksEndpointIdRouteImport.update({
  id: '/webhooks/$endpointId',
  path: '/webhooks/$endpointId',
  getParentRoute: () => AdminRoute,
} as any)
const PlatformSanctionsIndexRoute = PlatformSanctionsIndexRouteImport.update({
  id: '/sanctions/',
  path: '/sanctions/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSanctionsIdRoute = PlatformSanctionsIdRouteImport.update({
  id: '/sanctions/$id',
  path: '/sanctions/$id',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformWorkspacesIdRoute = PlatformWorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/request-access': typeof AuthRequestAccessRoute
  '/unsubscribe': typeof AuthUnsubscribeRoute
  '/$': typeof PortalSplatRoute
  '/search': typeof PortalSearchRoute
  '/settings': typeof PortalSettingsRouteWithChildren
  '/sign': typeof PortalSignRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/search': typeof AdminSearchRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/cells': typeof PlatformCellsRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/operators': typeof PlatformOperatorsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/enrol': typeof PlatformEnrolRoute
  '/admin/': typeof AdminIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/auth/magic-link': typeof AuthAuthMagicLinkRoute
  '/auth/popup': typeof AuthAuthPopupRoute
  '/auth/step-up': typeof AuthAuthStepUpRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/login/verify': typeof AuthLoginVerifyRoute
  '/s/$token': typeof AuthSTokenRoute
  '/p/$slug': typeof PortalPSlugRoute
  '/settings/delegates': typeof PortalSettingsDelegatesRoute
  '/settings/security': typeof PortalSettingsSecurityRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/legal/$documentId': typeof AdminLegalDocumentIdRoute
  '/admin/people/$membershipId': typeof AdminPeopleMembershipIdRoute
  '/admin/settings/access': typeof AdminSettingsAccessRoute
  '/admin/settings/ai': typeof AdminSettingsAiRoute
  '/admin/settings/danger': typeof AdminSettingsDangerRoute
  '/admin/settings/export': typeof AdminSettingsExportRoute
  '/admin/settings/residency': typeof AdminSettingsResidencyRoute
  '/admin/webhooks/$endpointId': typeof AdminWebhooksEndpointIdRoute
  '/platform/sanctions/$id': typeof PlatformSanctionsIdRoute
  '/platform/workspaces/$id': typeof PlatformWorkspacesIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/settings/': typeof PortalSettingsIndexRoute
  '/admin/access-requests/': typeof AdminAccessRequestsIndexRoute
  '/admin/access-review/': typeof AdminAccessReviewIndexRoute
  '/admin/accreditation/': typeof AdminAccreditationIndexRoute
  '/admin/api-keys/': typeof AdminApiKeysIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/branding/': typeof AdminBrandingIndexRoute
  '/admin/domains/': typeof AdminDomainsIndexRoute
  '/admin/embed/': typeof AdminEmbedIndexRoute
  '/admin/esign/': typeof AdminEsignIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/health/': typeof AdminHealthIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/legal/': typeof AdminLegalIndexRoute
  '/admin/mail/': typeof AdminMailIndexRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/share-links/': typeof AdminShareLinksIndexRoute
  '/admin/sso/': typeof AdminSsoIndexRoute
  '/admin/webhooks/': typeof AdminWebhooksIndexRoute
  '/platform/sanctions/': typeof PlatformSanctionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PortalIndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/request-access': typeof AuthRequestAccessRoute
  '/unsubscribe': typeof AuthUnsubscribeRoute
  '/$': typeof PortalSplatRoute
  '/search': typeof PortalSearchRoute
  '/sign': typeof PortalSignRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/search': typeof AdminSearchRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/cells': typeof PlatformCellsRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/operators': typeof PlatformOperatorsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/enrol': typeof PlatformEnrolRoute
  '/admin': typeof AdminIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/auth/magic-link': typeof AuthAuthMagicLinkRoute
  '/auth/popup': typeof AuthAuthPopupRoute
  '/auth/step-up': typeof AuthAuthStepUpRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/login/verify': typeof AuthLoginVerifyRoute
  '/s/$token': typeof AuthSTokenRoute
  '/p/$slug': typeof PortalPSlugRoute
  '/settings/delegates': typeof PortalSettingsDelegatesRoute
  '/settings/security': typeof PortalSettingsSecurityRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/legal/$documentId': typeof AdminLegalDocumentIdRoute
  '/admin/people/$membershipId': typeof AdminPeopleMembershipIdRoute
  '/admin/settings/access': typeof AdminSettingsAccessRoute
  '/admin/settings/ai': typeof AdminSettingsAiRoute
  '/admin/settings/danger': typeof AdminSettingsDangerRoute
  '/admin/settings/export': typeof AdminSettingsExportRoute
  '/admin/settings/residency': typeof AdminSettingsResidencyRoute
  '/admin/webhooks/$endpointId': typeof AdminWebhooksEndpointIdRoute
  '/platform/sanctions/$id': typeof PlatformSanctionsIdRoute
  '/platform/workspaces/$id': typeof PlatformWorkspacesIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/settings': typeof PortalSettingsIndexRoute
  '/admin/access-requests': typeof AdminAccessRequestsIndexRoute
  '/admin/access-review': typeof AdminAccessReviewIndexRoute
  '/admin/accreditation': typeof AdminAccreditationIndexRoute
  '/admin/api-keys': typeof AdminApiKeysIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/billing': typeof AdminBillingIndexRoute
  '/admin/branding': typeof AdminBrandingIndexRoute
  '/admin/domains': typeof AdminDomainsIndexRoute
  '/admin/embed': typeof AdminEmbedIndexRoute
  '/admin/esign': typeof AdminEsignIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/health': typeof AdminHealthIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/legal': typeof AdminLegalIndexRoute
  '/admin/mail': typeof AdminMailIndexRoute
  '/admin/modules': typeof AdminModulesIndexRoute
  '/admin/people': typeof AdminPeopleIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/share-links': typeof AdminShareLinksIndexRoute
  '/admin/sso': typeof AdminSsoIndexRoute
  '/admin/webhooks': typeof AdminWebhooksIndexRoute
  '/platform/sanctions': typeof PlatformSanctionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_auth/request-access': typeof AuthRequestAccessRoute
  '/_auth/unsubscribe': typeof AuthUnsubscribeRoute
  '/_portal/$': typeof PortalSplatRoute
  '/_portal/search': typeof PortalSearchRoute
  '/_portal/settings': typeof PortalSettingsRouteWithChildren
  '/_portal/sign': typeof PortalSignRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/search': typeof AdminSearchRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/cells': typeof PlatformCellsRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/operators': typeof PlatformOperatorsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform_/enrol': typeof PlatformEnrolRoute
  '/_portal/': typeof PortalIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/_auth/auth/magic-link': typeof AuthAuthMagicLinkRoute
  '/_auth/auth/popup': typeof AuthAuthPopupRoute
  '/_auth/auth/step-up': typeof AuthAuthStepUpRoute
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_auth/login/verify': typeof AuthLoginVerifyRoute
  '/_auth/s/$token': typeof AuthSTokenRoute
  '/_portal/p/$slug': typeof PortalPSlugRoute
  '/_portal/settings/delegates': typeof PortalSettingsDelegatesRoute
  '/_portal/settings/security': typeof PortalSettingsSecurityRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/legal/$documentId': typeof AdminLegalDocumentIdRoute
  '/admin/people/$membershipId': typeof AdminPeopleMembershipIdRoute
  '/admin/settings/access': typeof AdminSettingsAccessRoute
  '/admin/settings/ai': typeof AdminSettingsAiRoute
  '/admin/settings/danger': typeof AdminSettingsDangerRoute
  '/admin/settings/export': typeof AdminSettingsExportRoute
  '/admin/settings/residency': typeof AdminSettingsResidencyRoute
  '/admin/webhooks/$endpointId': typeof AdminWebhooksEndpointIdRoute
  '/platform/sanctions/$id': typeof PlatformSanctionsIdRoute
  '/platform/workspaces/$id': typeof PlatformWorkspacesIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_portal/settings/': typeof PortalSettingsIndexRoute
  '/admin/access-requests/': typeof AdminAccessRequestsIndexRoute
  '/admin/access-review/': typeof AdminAccessReviewIndexRoute
  '/admin/accreditation/': typeof AdminAccreditationIndexRoute
  '/admin/api-keys/': typeof AdminApiKeysIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/branding/': typeof AdminBrandingIndexRoute
  '/admin/domains/': typeof AdminDomainsIndexRoute
  '/admin/embed/': typeof AdminEmbedIndexRoute
  '/admin/esign/': typeof AdminEsignIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/health/': typeof AdminHealthIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/legal/': typeof AdminLegalIndexRoute
  '/admin/mail/': typeof AdminMailIndexRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/share-links/': typeof AdminShareLinksIndexRoute
  '/admin/sso/': typeof AdminSsoIndexRoute
  '/admin/webhooks/': typeof AdminWebhooksIndexRoute
  '/platform/sanctions/': typeof PlatformSanctionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/admin'
    | '/platform'
    | '/setup'
    | '/signup'
    | '/request-access'
    | '/unsubscribe'
    | '/$'
    | '/search'
    | '/settings'
    | '/sign'
    | '/admin/$'
    | '/admin/search'
    | '/platform/audit'
    | '/platform/cells'
    | '/platform/health'
    | '/platform/operators'
    | '/platform/plans'
    | '/platform/enrol'
    | '/admin/'
    | '/platform/'
    | '/auth/magic-link'
    | '/auth/popup'
    | '/auth/step-up'
    | '/invite/$token'
    | '/login/verify'
    | '/s/$token'
    | '/p/$slug'
    | '/settings/delegates'
    | '/settings/security'
    | '/admin/groups/$groupId'
    | '/admin/legal/$documentId'
    | '/admin/people/$membershipId'
    | '/admin/settings/access'
    | '/admin/settings/ai'
    | '/admin/settings/danger'
    | '/admin/settings/export'
    | '/admin/settings/residency'
    | '/admin/webhooks/$endpointId'
    | '/platform/sanctions/$id'
    | '/platform/workspaces/$id'
    | '/login/'
    | '/settings/'
    | '/admin/access-requests/'
    | '/admin/access-review/'
    | '/admin/accreditation/'
    | '/admin/api-keys/'
    | '/admin/audit/'
    | '/admin/billing/'
    | '/admin/branding/'
    | '/admin/domains/'
    | '/admin/embed/'
    | '/admin/esign/'
    | '/admin/groups/'
    | '/admin/health/'
    | '/admin/integrations/'
    | '/admin/jobs/'
    | '/admin/legal/'
    | '/admin/mail/'
    | '/admin/modules/'
    | '/admin/people/'
    | '/admin/settings/'
    | '/admin/share-links/'
    | '/admin/sso/'
    | '/admin/webhooks/'
    | '/platform/sanctions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/setup'
    | '/signup'
    | '/request-access'
    | '/unsubscribe'
    | '/$'
    | '/search'
    | '/sign'
    | '/admin/$'
    | '/admin/search'
    | '/platform/audit'
    | '/platform/cells'
    | '/platform/health'
    | '/platform/operators'
    | '/platform/plans'
    | '/platform/enrol'
    | '/admin'
    | '/platform'
    | '/auth/magic-link'
    | '/auth/popup'
    | '/auth/step-up'
    | '/invite/$token'
    | '/login/verify'
    | '/s/$token'
    | '/p/$slug'
    | '/settings/delegates'
    | '/settings/security'
    | '/admin/groups/$groupId'
    | '/admin/legal/$documentId'
    | '/admin/people/$membershipId'
    | '/admin/settings/access'
    | '/admin/settings/ai'
    | '/admin/settings/danger'
    | '/admin/settings/export'
    | '/admin/settings/residency'
    | '/admin/webhooks/$endpointId'
    | '/platform/sanctions/$id'
    | '/platform/workspaces/$id'
    | '/login'
    | '/settings'
    | '/admin/access-requests'
    | '/admin/access-review'
    | '/admin/accreditation'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/domains'
    | '/admin/embed'
    | '/admin/esign'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/legal'
    | '/admin/mail'
    | '/admin/modules'
    | '/admin/people'
    | '/admin/settings'
    | '/admin/share-links'
    | '/admin/sso'
    | '/admin/webhooks'
    | '/platform/sanctions'
  id:
    | '__root__'
    | '/_auth'
    | '/_portal'
    | '/accessibility'
    | '/admin'
    | '/platform'
    | '/setup'
    | '/signup'
    | '/_auth/request-access'
    | '/_auth/unsubscribe'
    | '/_portal/$'
    | '/_portal/search'
    | '/_portal/settings'
    | '/_portal/sign'
    | '/admin/$'
    | '/admin/search'
    | '/platform/audit'
    | '/platform/cells'
    | '/platform/health'
    | '/platform/operators'
    | '/platform/plans'
    | '/platform_/enrol'
    | '/_portal/'
    | '/admin/'
    | '/platform/'
    | '/_auth/auth/magic-link'
    | '/_auth/auth/popup'
    | '/_auth/auth/step-up'
    | '/_auth/invite/$token'
    | '/_auth/login/verify'
    | '/_auth/s/$token'
    | '/_portal/p/$slug'
    | '/_portal/settings/delegates'
    | '/_portal/settings/security'
    | '/admin/groups/$groupId'
    | '/admin/legal/$documentId'
    | '/admin/people/$membershipId'
    | '/admin/settings/access'
    | '/admin/settings/ai'
    | '/admin/settings/danger'
    | '/admin/settings/export'
    | '/admin/settings/residency'
    | '/admin/webhooks/$endpointId'
    | '/platform/sanctions/$id'
    | '/platform/workspaces/$id'
    | '/_auth/login/'
    | '/_portal/settings/'
    | '/admin/access-requests/'
    | '/admin/access-review/'
    | '/admin/accreditation/'
    | '/admin/api-keys/'
    | '/admin/audit/'
    | '/admin/billing/'
    | '/admin/branding/'
    | '/admin/domains/'
    | '/admin/embed/'
    | '/admin/esign/'
    | '/admin/groups/'
    | '/admin/health/'
    | '/admin/integrations/'
    | '/admin/jobs/'
    | '/admin/legal/'
    | '/admin/mail/'
    | '/admin/modules/'
    | '/admin/people/'
    | '/admin/settings/'
    | '/admin/share-links/'
    | '/admin/sso/'
    | '/admin/webhooks/'
    | '/platform/sanctions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  PlatformEnrolRoute: typeof PlatformEnrolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/request-access': {
      id: '/_auth/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof AuthRequestAccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unsubscribe': {
      id: '/_auth/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof AuthUnsubscribeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/$': {
      id: '/_portal/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PortalSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/search': {
      id: '/_portal/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PortalSearchRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/settings': {
      id: '/_portal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/sign': {
      id: '/_portal/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof PortalSignRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/cells': {
      id: '/platform/cells'
      path: '/cells'
      fullPath: '/platform/cells'
      preLoaderRoute: typeof PlatformCellsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/health': {
      id: '/platform/health'
      path: '/health'
      fullPath: '/platform/health'
      preLoaderRoute: typeof PlatformHealthRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/operators': {
      id: '/platform/operators'
      path: '/operators'
      fullPath: '/platform/operators'
      preLoaderRoute: typeof PlatformOperatorsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/plans': {
      id: '/platform/plans'
      path: '/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform_/enrol': {
      id: '/platform_/enrol'
      path: '/platform/enrol'
      fullPath: '/platform/enrol'
      preLoaderRoute: typeof PlatformEnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/magic-link': {
      id: '/_auth/auth/magic-link'
      path: '/auth/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthAuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/popup': {
      id: '/_auth/auth/popup'
      path: '/auth/popup'
      fullPath: '/auth/popup'
      preLoaderRoute: typeof AuthAuthPopupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/step-up': {
      id: '/_auth/auth/step-up'
      path: '/auth/step-up'
      fullPath: '/auth/step-up'
      preLoaderRoute: typeof AuthAuthStepUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/verify': {
      id: '/_auth/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof AuthLoginVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/s/$token': {
      id: '/_auth/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof AuthSTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_portal/p/$slug': {
      id: '/_portal/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PortalPSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/settings/': {
      id: '/_portal/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof PortalSettingsIndexRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/_portal/settings/delegates': {
      id: '/_portal/settings/delegates'
      path: '/delegates'
      fullPath: '/settings/delegates'
      preLoaderRoute: typeof PortalSettingsDelegatesRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/_portal/settings/security': {
      id: '/_portal/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof PortalSettingsSecurityRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/admin/access-requests/': {
      id: '/admin/access-requests/'
      path: '/access-requests'
      fullPath: '/admin/access-requests/'
      preLoaderRoute: typeof AdminAccessRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-review/': {
      id: '/admin/access-review/'
      path: '/access-review'
      fullPath: '/admin/access-review/'
      preLoaderRoute: typeof AdminAccessReviewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accreditation/': {
      id: '/admin/accreditation/'
      path: '/accreditation'
      fullPath: '/admin/accreditation/'
      preLoaderRoute: typeof AdminAccreditationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys/': {
      id: '/admin/api-keys/'
      path: '/api-keys'
      fullPath: '/admin/api-keys/'
      preLoaderRoute: typeof AdminApiKeysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding/': {
      id: '/admin/branding/'
      path: '/branding'
      fullPath: '/admin/branding/'
      preLoaderRoute: typeof AdminBrandingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains/': {
      id: '/admin/domains/'
      path: '/domains'
      fullPath: '/admin/domains/'
      preLoaderRoute: typeof AdminDomainsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/embed/': {
      id: '/admin/embed/'
      path: '/embed'
      fullPath: '/admin/embed/'
      preLoaderRoute: typeof AdminEmbedIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/esign/': {
      id: '/admin/esign/'
      path: '/esign'
      fullPath: '/admin/esign/'
      preLoaderRoute: typeof AdminEsignIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups/$groupId': {
      id: '/admin/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AdminGroupsGroupIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health/': {
      id: '/admin/health/'
      path: '/health'
      fullPath: '/admin/health/'
      preLoaderRoute: typeof AdminHealthIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/integrations'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal/': {
      id: '/admin/legal/'
      path: '/legal'
      fullPath: '/admin/legal/'
      preLoaderRoute: typeof AdminLegalIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal/$documentId': {
      id: '/admin/legal/$documentId'
      path: '/legal/$documentId'
      fullPath: '/admin/legal/$documentId'
      preLoaderRoute: typeof AdminLegalDocumentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail/': {
      id: '/admin/mail/'
      path: '/mail'
      fullPath: '/admin/mail/'
      preLoaderRoute: typeof AdminMailIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules/': {
      id: '/admin/modules/'
      path: '/modules'
      fullPath: '/admin/modules/'
      preLoaderRoute: typeof AdminModulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people/': {
      id: '/admin/people/'
      path: '/people'
      fullPath: '/admin/people/'
      preLoaderRoute: typeof AdminPeopleIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people/$membershipId': {
      id: '/admin/people/$membershipId'
      path: '/people/$membershipId'
      fullPath: '/admin/people/$membershipId'
      preLoaderRoute: typeof AdminPeopleMembershipIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/access': {
      id: '/admin/settings/access'
      path: '/settings/access'
      fullPath: '/admin/settings/access'
      preLoaderRoute: typeof AdminSettingsAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/ai': {
      id: '/admin/settings/ai'
      path: '/settings/ai'
      fullPath: '/admin/settings/ai'
      preLoaderRoute: typeof AdminSettingsAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/danger': {
      id: '/admin/settings/danger'
      path: '/settings/danger'
      fullPath: '/admin/settings/danger'
      preLoaderRoute: typeof AdminSettingsDangerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/export': {
      id: '/admin/settings/export'
      path: '/settings/export'
      fullPath: '/admin/settings/export'
      preLoaderRoute: typeof AdminSettingsExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/residency': {
      id: '/admin/settings/residency'
      path: '/settings/residency'
      fullPath: '/admin/settings/residency'
      preLoaderRoute: typeof AdminSettingsResidencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/share-links/': {
      id: '/admin/share-links/'
      path: '/share-links'
      fullPath: '/admin/share-links/'
      preLoaderRoute: typeof AdminShareLinksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sso/': {
      id: '/admin/sso/'
      path: '/sso'
      fullPath: '/admin/sso/'
      preLoaderRoute: typeof AdminSsoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks/': {
      id: '/admin/webhooks/'
      path: '/webhooks'
      fullPath: '/admin/webhooks/'
      preLoaderRoute: typeof AdminWebhooksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks/$endpointId': {
      id: '/admin/webhooks/$endpointId'
      path: '/webhooks/$endpointId'
      fullPath: '/admin/webhooks/$endpointId'
      preLoaderRoute: typeof AdminWebhooksEndpointIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/platform/sanctions/': {
      id: '/platform/sanctions/'
      path: '/sanctions'
      fullPath: '/platform/sanctions/'
      preLoaderRoute: typeof PlatformSanctionsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/sanctions/$id': {
      id: '/platform/sanctions/$id'
      path: '/sanctions/$id'
      fullPath: '/platform/sanctions/$id'
      preLoaderRoute: typeof PlatformSanctionsIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/workspaces/$id': {
      id: '/platform/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/platform/workspaces/$id'
      preLoaderRoute: typeof PlatformWorkspacesIdRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRequestAccessRoute: typeof AuthRequestAccessRoute
  AuthUnsubscribeRoute: typeof AuthUnsubscribeRoute
  AuthAuthMagicLinkRoute: typeof AuthAuthMagicLinkRoute
  AuthAuthPopupRoute: typeof AuthAuthPopupRoute
  AuthAuthStepUpRoute: typeof AuthAuthStepUpRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
  AuthLoginVerifyRoute: typeof AuthLoginVerifyRoute
  AuthSTokenRoute: typeof AuthSTokenRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRequestAccessRoute: AuthRequestAccessRoute,
  AuthUnsubscribeRoute: AuthUnsubscribeRoute,
  AuthAuthMagicLinkRoute: AuthAuthMagicLinkRoute,
  AuthAuthPopupRoute: AuthAuthPopupRoute,
  AuthAuthStepUpRoute: AuthAuthStepUpRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
  AuthLoginVerifyRoute: AuthLoginVerifyRoute,
  AuthSTokenRoute: AuthSTokenRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalSettingsRouteChildren {
  PortalSettingsDelegatesRoute: typeof PortalSettingsDelegatesRoute
  PortalSettingsSecurityRoute: typeof PortalSettingsSecurityRoute
  PortalSettingsIndexRoute: typeof PortalSettingsIndexRoute
}

const PortalSettingsRouteChildren: PortalSettingsRouteChildren = {
  PortalSettingsDelegatesRoute: PortalSettingsDelegatesRoute,
  PortalSettingsSecurityRoute: PortalSettingsSecurityRoute,
  PortalSettingsIndexRoute: PortalSettingsIndexRoute,
}

const PortalSettingsRouteWithChildren = PortalSettingsRoute._addFileChildren(
  PortalSettingsRouteChildren,
)

interface PortalRouteChildren {
  PortalSplatRoute: typeof PortalSplatRoute
  PortalSearchRoute: typeof PortalSearchRoute
  PortalSettingsRoute: typeof PortalSettingsRouteWithChildren
  PortalSignRoute: typeof PortalSignRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalPSlugRoute: typeof PortalPSlugRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSplatRoute: PortalSplatRoute,
  PortalSearchRoute: PortalSearchRoute,
  PortalSettingsRoute: PortalSettingsRouteWithChildren,
  PortalSignRoute: PortalSignRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalPSlugRoute: PortalPSlugRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminGroupsGroupIdRoute: typeof AdminGroupsGroupIdRoute
  AdminLegalDocumentIdRoute: typeof AdminLegalDocumentIdRoute
  AdminPeopleMembershipIdRoute: typeof AdminPeopleMembershipIdRoute
  AdminSettingsAccessRoute: typeof AdminSettingsAccessRoute
  AdminSettingsAiRoute: typeof AdminSettingsAiRoute
  AdminSettingsDangerRoute: typeof AdminSettingsDangerRoute
  AdminSettingsExportRoute: typeof AdminSettingsExportRoute
  AdminSettingsResidencyRoute: typeof AdminSettingsResidencyRoute
  AdminWebhooksEndpointIdRoute: typeof AdminWebhooksEndpointIdRoute
  AdminAccessRequestsIndexRoute: typeof AdminAccessRequestsIndexRoute
  AdminAccessReviewIndexRoute: typeof AdminAccessReviewIndexRoute
  AdminAccreditationIndexRoute: typeof AdminAccreditationIndexRoute
  AdminApiKeysIndexRoute: typeof AdminApiKeysIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
  AdminBrandingIndexRoute: typeof AdminBrandingIndexRoute
  AdminDomainsIndexRoute: typeof AdminDomainsIndexRoute
  AdminEmbedIndexRoute: typeof AdminEmbedIndexRoute
  AdminEsignIndexRoute: typeof AdminEsignIndexRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
  AdminHealthIndexRoute: typeof AdminHealthIndexRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminLegalIndexRoute: typeof AdminLegalIndexRoute
  AdminMailIndexRoute: typeof AdminMailIndexRoute
  AdminModulesIndexRoute: typeof AdminModulesIndexRoute
  AdminPeopleIndexRoute: typeof AdminPeopleIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminShareLinksIndexRoute: typeof AdminShareLinksIndexRoute
  AdminSsoIndexRoute: typeof AdminSsoIndexRoute
  AdminWebhooksIndexRoute: typeof AdminWebhooksIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminGroupsGroupIdRoute: AdminGroupsGroupIdRoute,
  AdminLegalDocumentIdRoute: AdminLegalDocumentIdRoute,
  AdminPeopleMembershipIdRoute: AdminPeopleMembershipIdRoute,
  AdminSettingsAccessRoute: AdminSettingsAccessRoute,
  AdminSettingsAiRoute: AdminSettingsAiRoute,
  AdminSettingsDangerRoute: AdminSettingsDangerRoute,
  AdminSettingsExportRoute: AdminSettingsExportRoute,
  AdminSettingsResidencyRoute: AdminSettingsResidencyRoute,
  AdminWebhooksEndpointIdRoute: AdminWebhooksEndpointIdRoute,
  AdminAccessRequestsIndexRoute: AdminAccessRequestsIndexRoute,
  AdminAccessReviewIndexRoute: AdminAccessReviewIndexRoute,
  AdminAccreditationIndexRoute: AdminAccreditationIndexRoute,
  AdminApiKeysIndexRoute: AdminApiKeysIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminBrandingIndexRoute: AdminBrandingIndexRoute,
  AdminDomainsIndexRoute: AdminDomainsIndexRoute,
  AdminEmbedIndexRoute: AdminEmbedIndexRoute,
  AdminEsignIndexRoute: AdminEsignIndexRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
  AdminHealthIndexRoute: AdminHealthIndexRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminLegalIndexRoute: AdminLegalIndexRoute,
  AdminMailIndexRoute: AdminMailIndexRoute,
  AdminModulesIndexRoute: AdminModulesIndexRoute,
  AdminPeopleIndexRoute: AdminPeopleIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminShareLinksIndexRoute: AdminShareLinksIndexRoute,
  AdminSsoIndexRoute: AdminSsoIndexRoute,
  AdminWebhooksIndexRoute: AdminWebhooksIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PlatformRouteChildren {
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformCellsRoute: typeof PlatformCellsRoute
  PlatformHealthRoute: typeof PlatformHealthRoute
  PlatformOperatorsRoute: typeof PlatformOperatorsRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformSanctionsIdRoute: typeof PlatformSanctionsIdRoute
  PlatformWorkspacesIdRoute: typeof PlatformWorkspacesIdRoute
  PlatformSanctionsIndexRoute: typeof PlatformSanctionsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformCellsRoute: PlatformCellsRoute,
  PlatformHealthRoute: PlatformHealthRoute,
  PlatformOperatorsRoute: PlatformOperatorsRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformSanctionsIdRoute: PlatformSanctionsIdRoute,
  PlatformWorkspacesIdRoute: PlatformWorkspacesIdRoute,
  PlatformSanctionsIndexRoute: PlatformSanctionsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  PlatformEnrolRoute: PlatformEnrolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
