export {
  type AuthzServiceWithEngine,
  ancestorsOf,
  DROP_WINDOW_DAYS,
  ENGINE_BATCH_CHUNK,
  ENGINE_RECONCILE_JOB,
  ENGINE_SYNC_JOB,
  type EngineOperation,
  RELATIONSHIP_ENGINE_MODES,
  type RelationshipEngineHandle,
  type RelationshipEngineMetrics,
  type RelationshipEngineMode,
  type SyncOutcome,
  type WithRelationshipEngineOptions,
  withRelationshipEngine,
} from "./engine.js";
export {
  delegatedSubjectsOf,
  earliestOf,
  gatesFor,
  gateVerdictExpiry,
  ipAllowed,
  ndaStamp,
  nodesOf,
  pendingGatesAtRebuild,
  type ResolvedNode,
  resolveNode,
  ruleIsLive,
  rulesCovering,
  rulesFor,
  settleGates,
  subjectsOf,
  withResolvedStamps,
} from "./evaluate.js";
export {
  type AuthzMatrix,
  AuthzMatrixError,
  apiKeyScopes,
  loadAuthzMatrix,
  MATRIX_PATH,
  type MatrixPermission,
  type MatrixRoute,
  parseAuthzMatrix,
  permissionsForRole,
  ROUTE_REQUIREMENTS,
  type RouteRequirement,
  renderAuthzMatrix,
  requirementTag,
  roleHasPermission,
  routeRequirement,
} from "./matrix.js";
export {
  DELEGATE_SCOPE_KINDS,
  DELEGATE_SCOPE_MODULES,
  type DelegateScopeName,
  type Delegation,
  delegateScopeAdmitsKind,
  type Gate,
  isAncestorOrSelf,
  isPendingGate,
  LTREE_PATH_RE,
  membershipExpired,
  type Principal,
  type PrincipalAttestation,
  pathDepth,
  type Rule,
  resourceKey,
  type StaffOnlyNode,
  SUBJECT_SPECIFICITY,
  subjectKey,
  veiledBy,
} from "./model.js";
export {
  computeEffectiveRows,
  locatedDocumentIds,
  type RebuildResult,
  rebuildEffectiveAccess,
} from "./rebuild.js";
export {
  type CreateGrantInput,
  type CreatePolicyInput,
  EffectiveAccessRepo,
  GrantRepo,
  gateOfRow,
  PolicyRepo,
  PrincipalRepo,
  parseTstzRange,
  ruleOfRow,
  staffOnlyNodes,
  subjectOfRow,
  toTstzRange,
  veilLocation,
} from "./repos/access-repo.js";
export {
  createEngineStore,
  createLeaseSyncLock,
  createLocalSyncLock,
  type EngineStateRow,
  type EngineStore,
  type EngineView,
  SYNC_BUSY,
  SYNC_LEASE_TTL_MS,
  type SyncLock,
} from "./repos/engine-state-repo.js";
export {
  derivedRulePath,
  lookupResource,
  type ResourceLookup,
  rederiveRulePaths,
  rederiveRulePathsFor,
} from "./repos/resource-repo.js";
export { buildRelationshipSnapshot } from "./repos/snapshot.js";
export { type MembershipLite, membershipSummary } from "./repos/state-repo.js";
export {
  type AuthzService,
  type AuthzServiceOptions,
  bumpAcl,
  createAuthzService,
  type ResourceKindPolicy,
} from "./service.js";
