export {
  createPostmarkMailer,
  DEFAULT_BROADCAST_STREAM,
  INACTIVE_RECIPIENT_ERROR,
  type MailAddress,
  MailerError,
  type MailerErrorCode,
  maskEmail,
  POSTMARK_API_BASE,
  POSTMARK_SUB_PROCESSOR,
  type PostmarkMailer,
  type PostmarkMailerOptions,
  PROVIDER_SUPPRESSED_PREFIX,
  parsePostmarkEvent,
  TRANSACTIONAL_STREAM,
} from "./postmark-mailer.js";
