import { type SQL, sql } from "drizzle-orm";
import {
  check,
  customType,
  index,
  integer,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { ltree } from "./access.js";
import { coreSchema, workspace } from "./core.js";

/*
 * Workspace search (E2.8, EXECUTION_PLAN §15 "Postgres FTS with ACL filtering").
 *
 * Typed view of `migrations/core/0013_search_portability_i18n.sql`; the SQL is authoritative
 * (ADR-0004) — the external-read policy (members / live group membership / core.has_access)
 * lives there. Rows are written by modules through `services.search` (`@fundroom/search`) and
 * rebuilt by the `search.reindex` job; `tsv` is generated by Postgres.
 */

/** `tsvector`; drizzle has no built-in type. Read-only (a generated column). */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

export const SEARCH_ACL_KINDS = ["members", "groups", "staff", "resource"] as const;
export type SearchAclKind = (typeof SEARCH_ACL_KINDS)[number];

export const searchEntry = coreSchema.table(
  "search_entry",
  {
    id: uuid("id").primaryKey().default(sql`core.uuidv7()`),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspace.id, { onDelete: "cascade" }),
    module: text("module").notNull(),
    kind: text("kind").notNull(),
    /** The entity a hit opens; no FK (it lives in the owning module's schema). */
    refId: uuid("ref_id").notNull(),
    part: text("part").notNull().default(""),
    title: text("title").notNull(),
    /** Plain text, at most 200 000 characters. */
    body: text("body").notNull().default(""),
    /** SPA path starting with "/". */
    href: text("href").notNull(),
    aclKind: text("acl_kind").notNull(),
    aclGroups: uuid("acl_groups").array(),
    aclResourceKind: text("acl_resource_kind"),
    aclResourceId: uuid("acl_resource_id"),
    aclPath: ltree("acl_path"),
    tsv: tsvector("tsv").generatedAlwaysAs(
      (): SQL =>
        sql`setweight(to_tsvector('simple'::regconfig, title), 'A') || setweight(to_tsvector('simple'::regconfig, body), 'C')`,
    ),
    sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }).notNull(),
    indexedAt: timestamp("indexed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("search_entry_ref_idx").on(t.workspaceId, t.module, t.kind, t.refId, t.part),
    index("search_entry_tsv_idx").using("gin", t.tsv),
    index("search_entry_title_trgm_idx").using("gin", t.title.op("gin_trgm_ops")),
    check("search_entry_acl_kind", sql`${t.aclKind} IN ('members', 'groups', 'staff', 'resource')`),
    check(
      "search_entry_acl_shape",
      sql`(${t.aclKind} = 'groups') = (${t.aclGroups} IS NOT NULL) AND (${t.aclKind} = 'resource') = (${t.aclResourceKind} IS NOT NULL AND ${t.aclResourceId} IS NOT NULL) AND (${t.aclPath} IS NULL OR ${t.aclKind} = 'resource')`,
    ),
    check("search_entry_href_shape", sql`${t.href} ~ '^/'`),
    check("search_entry_body_length", sql`char_length(${t.body}) <= 200000`),
  ],
);

/** Which provider version a workspace's entries of one module were built with. */
export const searchState = coreSchema.table(
  "search_state",
  {
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspace.id, { onDelete: "cascade" }),
    module: text("module").notNull(),
    version: integer("version").notNull(),
    indexedAt: timestamp("indexed_at", { withTimezone: true }).notNull().defaultNow(),
    /** Set by `requestReindex`; cleared by the reindex job. */
    requestedAt: timestamp("requested_at", { withTimezone: true }),
  },
  (t) => [primaryKey({ columns: [t.workspaceId, t.module] })],
);

export type SearchEntry = typeof searchEntry.$inferSelect;
export type NewSearchEntry = typeof searchEntry.$inferInsert;
export type SearchState = typeof searchState.$inferSelect;
